### ISSUE TITLE
Consider swapping pin 2 (+5V) and pin 7 (+24V)

### ISSUE THREAD

**Issue by Cougar** [InfernoEmbedded/onewire-softdevice#4]
Is there any reasoning behind your RJ45 pinout?

This is what happens right now when you accidentally put Ethernet crossover cable between 1W controller and 1W device:

| RJ45 Pin  | Signal | Signal | RJ45 Pin
| :-------: | :----- | :----- |  :-------: |
| 1 | Gnd | Gnd | 3 |
| 2 | +5V | N/C | 6 |
| 3 | Gnd | Gnd | 1 |
| 4 | 1W Data | +24V | 7 |
| 5 | Gnd | Gnd | 8 |
| 6 | N/C | +5V | 2 |
| 7 | +24V | 1W Data | 4 |
| 8 | Gnd | Gnd | 5 |

I'm worried a bit that in this case the +24V and 1W data gets swapped and this could be lethal for 1W device. Much better is when 5V will be feed to 1W bus which just does not work but the device should handle without any [issues](https://www.maximintegrated.com/en/app-notes/index.mvp/id/1796). Otherwise I love the pin selection which keeps GND-s connecet even with wrong cable.

**Comment by deece** [comment]
It's a defacto standard for 1wire over cat5. Btw, that's not how crossovers are wired, they swap the orange and green pairs, the rest stay the same.

**Comment by Cougar** [comment]
Sometimes pairs 4-5 and 7-8 are also swapped in crossover cables. I now see that many use such pinout. Feels dangerous for me but I admit that it is good to stick with standards. Thanks for explanations.
