### ISSUE TITLE
Problem with rgbw softdevice

### ISSUE THREAD

**Issue by eldrik** [InfernoEmbedded/onewire-softdevice#5]
There is a problem with the rgbw softdevice sketch or perhaps the mbed environment, the sketch is not running proper and seems to stop after the following code snippet

__HAL_TIM_ENABLE_IT(&htim15, TIM_IT_UPDATE);

**Comment by deece** [comment]
Looks like it's related to this: https://stackoverflow.com/questions/53997196/gcc-8-for-arm-in-lto-mode-is-removing-interrupt-handlers-and-weak-functions-ho

**Comment by eldrik** [comment]
Any chance to test it? I am not that deep into what's discussed in the stackoverflow thread to handle it by myself.

**Comment by deece** [comment]
I'm working on it, I'll push a solution once I have it.

**Comment by deece** [comment]
Fixed with a7e649f3c7f0ae6ab8934cfd59c72fbca2f0cb79. Try the binaries that are in the master branch now.

**Comment by eldrik** [comment]
The problem is resolved the controller is recognized and setting rgbw colors is possible.

But there seems to be a problem with the color fading I opened another issue 

https://github.com/InfernoEmbedded/onewire-softdevice/issues/6

Regards
