### ISSUE TITLE
Problem with color transition on rgbw device

### ISSUE THREAD

**Issue by eldrik** [InfernoEmbedded/onewire-softdevice#6]
When sending a color transition to a 12V rgb stripe on the rgbw controller for example on channel1 

from 

000,255,000,000,15000

to 

255,255,000,000,15000

the transition looks normal, color rises from low to high brightness if trying the other way around from

255,255,0,0,15000

to

000,255,000,000,15000

the fading color immediately  drops down to a low brightness value returning to a higher brightness value after some seconds and continues the transition phase with the normal fade out of the fading color.

If trying to lower a color value for example 

from 

255,255,0,0,15000

to 

125,125,0,0,15000

the brightness immediatly drops down continuing with the total fade out of both colors and after some seconds continues on both colors with a higher brightness value and ends on the desired value at the end of the transition time. 

Another curiosity is happening when trying to read the channel it results in 

0,  0,  0,  0,11993088

Is this a hardware fault or is there something wrong with the transition function?

**Comment by deece** [comment]
This should be fixed by d33c8252542624dd87d4f5c35f3b91f3efe617e8

**Comment by eldrik** [comment]
Fixed
