### ISSUE TITLE
getChannel function wrong channel input?

### ISSUE THREAD

**Issue by eldrik** [InfernoEmbedded/onewire-softdevice#7]
Hi,

Shouldn't  the channel number reflect the channel?

case 0 = channel0, case 1 = channel1 and so on?

void getChannel(uint8_t channel, ChannelData &data) {
switch (channel) {
case 0:
			channel0.getCurrent(data);
break;
case 1:
			channel0.getCurrent(data);
break;
#if CHANNELS_4
case 2:
			channel0.getCurrent(data);
break;
case 3:
			channel0.getCurrent(data);
break;
#endif

Regards
eldrik

**Comment by deece** [comment]
Yeah, it should, copy and paste Monster :)

**Comment by deece** [comment]
Fixed with 4e6c5e0c628655fee792bf3d0fb7536c97bc16b1

**Comment by eldrik** [comment]
Fixed but there seems to be problem with requesting the acual color value and fade time

https://github.com/InfernoEmbedded/onewire-softdevice/issues/8
