### ISSUE TITLE
getChannel function does not return the actual color value and fade time

### ISSUE THREAD

**Issue by eldrik** [InfernoEmbedded/onewire-softdevice#8]
Hi,

requesting the last color value of a channel via "get rgbw_channel1" results not in the last set color value and shows a high remaining transition time.

Examples:

1) setting rgbw_channel1 to 255,255,255,0,0 and requesting the value via the get command results in 0,  0,  0,  0,11993088

2) setting the value 125,125,125,0,0 and getting the value results in 86, 86, 86,  0,11993088

3) Doing a fade from 255,255,255,0,0 to 0,0,0,0,60000 and getting the channel value each 15sec restults in

40, 40, 40,  0,12037808

2,  2,  2,  0,12022968

118,118,118,  0,12008688

0,  0,  0,  0,11993088

Hope you can retrace it.

Regards
eldrik

**Comment by deece** [comment]
This should be fixed by d33c8252542624dd87d4f5c35f3b91f3efe617e8

**Comment by eldrik** [comment]
fixed
